### ISSUE TITLE
main.mm change

### ISSUE THREAD

**Issue by ofZach** [brightredchilli/swiftcontrol#8]
it seems like you can do this in ofApp::setup -- I guess it's cleaner then using the 0.3 second delay: 

```
ofApp * app;
//--------------------------------------------------------------
void ofApp::setup(){
    
    app = this;
    
    ofxiOSAppDelegate *del = [UIApplication sharedApplication].delegate;
    UIViewController *parentVC = del.glViewController;
    
    ControlsViewController * controller = [[ControlsViewController alloc] initWithNibName:nil
                                                                                   bundle:nil];
    controller.app = [[ofAppAdapter alloc] initWithApp:app];
    [parentVC addChildViewController:controller];
    [parentVC.view addSubview:controller.view];
    [controller.view autoPinEdgesToSuperviewEdges];
```

**Comment by ofZach** [comment]
this helps! also less visual glitch on launch...  closing...

**Comment by brightredchilli** [comment]
yes! This does look like a pretty clean solution! I wonder though, there is a hidden dependency between when setup gets called, and when the glViewController gets instantiated. I'm not familiar enough to know whether this order might be changed at some point in the future.

**Comment by ofZach** [comment]
I'm pretty sure gl will always exist before setup -- since we need to do stuff in setup like load data into texture, etc. 

This change def helps with weird visual pops I was seeing on launch based on the 0.3 sec timeout....
